// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6KgAQklVxrSTd7fsJYsGrNQXtfpHyFGU',
    appId: '1:546109913704:web:55c9023012119e446c99dd',
    messagingSenderId: '546109913704',
    projectId: 'shelf-fa210',
    authDomain: 'shelf-fa210.firebaseapp.com',
    storageBucket: 'shelf-fa210.appspot.com',
    measurementId: 'G-1K2DP4EQ6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5TTtWNh1e6dWXiNibJb_wPllbfwOCgts',
    appId: '1:546109913704:android:e287f5b3355535b06c99dd',
    messagingSenderId: '546109913704',
    projectId: 'shelf-fa210',
    storageBucket: 'shelf-fa210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwgeuzT3Fhq79zVCfdUCLpq2GIXcX5R4',
    appId: '1:546109913704:ios:8587bbc51fb122346c99dd',
    messagingSenderId: '546109913704',
    projectId: 'shelf-fa210',
    storageBucket: 'shelf-fa210.appspot.com',
    iosBundleId: 'com.example.shelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJwgeuzT3Fhq79zVCfdUCLpq2GIXcX5R4',
    appId: '1:546109913704:ios:8587bbc51fb122346c99dd',
    messagingSenderId: '546109913704',
    projectId: 'shelf-fa210',
    storageBucket: 'shelf-fa210.appspot.com',
    iosBundleId: 'com.example.shelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6KgAQklVxrSTd7fsJYsGrNQXtfpHyFGU',
    appId: '1:546109913704:web:b14b191cde2d787e6c99dd',
    messagingSenderId: '546109913704',
    projectId: 'shelf-fa210',
    authDomain: 'shelf-fa210.firebaseapp.com',
    storageBucket: 'shelf-fa210.appspot.com',
    measurementId: 'G-PHY7KGWNRM',
  );
}
